"""Train a YOLO11 detector with a high-resolution small-pest configuration."""
from __future__ import annotations

import argparse
from pathlib import Path

from ultralytics import YOLO


def main():
    parser = argparse.ArgumentParser(description="Train YOLO11 for rice/maize pest and disease detection.")
    parser.add_argument("--data", type=Path, required=True, help="YOLO dataset.yaml generated by prepare_yolo11_dataset.py")
    parser.add_argument("--model", default="yolo11s.pt", help="Pretrained YOLO11 checkpoint (use yolo11m.pt when memory allows)")
    parser.add_argument("--epochs", type=int, default=150)
    parser.add_argument("--imgsz", type=int, default=1280, help="Large input preserves small insects")
    parser.add_argument("--batch", type=int, default=-1, help="-1 auto-selects a safe batch size")
    parser.add_argument("--device", default=None, help="GPU id such as 0, cpu, or omit for automatic selection")
    parser.add_argument("--project", default="runs")
    parser.add_argument("--name", default="pest_disease_yolo11")
    args = parser.parse_args()
    if not args.data.is_file():
        raise SystemExit(f"Dataset configuration not found: {args.data}")
    model = YOLO(args.model)
    model.train(
        data=str(args.data.resolve()), epochs=args.epochs, imgsz=args.imgsz,
        batch=args.batch, device=args.device, project=args.project, name=args.name,
        pretrained=True, patience=35, cache=False, optimizer="auto", cos_lr=True,
        mosaic=0.35, close_mosaic=20, mixup=0.05, copy_paste=0.15,
        degrees=8, translate=0.08, scale=0.35, fliplr=0.5, multi_scale=True,
        workers=4, seed=42, plots=True,
    )
    print(f"Training complete. Best checkpoint: {model.trainer.save_dir / 'weights' / 'best.pt'}")


if __name__ == "__main__":
    main()
